OrleansContrib/OrleansTestKit

src/OrleansTestKit/Streams/TestStreamId.cs
src/OrleansTestKit/Streams/TestStreamProvider.cs
src/OrleansTestKit/TestGrainFactory.cs
src/OrleansTestKit/TestGrainIdentity.cs
src/OrleansTestKit/TestKitSilo.cs
test/OrleansTestKit.Tests/BasicGrainTests.cs
test/OrleansTestKit.Tests/GrainProbeTests.cs
test/OrleansTestKit.Tests/StrictGrainProbeTests.cs
test/TestGrains/BasicGrains.cs
test/TestGrains/HelloGrain.cs
test/TestGrains/LifecycleGrain.cs
test/TestGrains/TestGrains.csproj
test/TestInterfaces/IBasicGrains.cs
test/TestInterfaces/ILifecycleGrain.cs
test/TestInterfaces/TestInterfaces.csproj

- Added grain deactivation methods to TestKitSilo
- Added additional unit tests

Grain Deactivation & general cleanup

---

src/OrleansTestKit/OrleansTestKit.csproj
src/OrleansTestKit/TestKitOptions.cs
src/OrleansTestKit/TestKitSilo.cs
src/OrleansTestKit/TestServiceProvider.cs
test/OrleansTestKit.Tests/OrleansTestKit.Tests.csproj
test/OrleansTestKit.Tests/ServiceProbeTests.cs
test/TestGrains/HelloGrainWithServiceDependency.cs
test/TestGrains/TestGrains.csproj
test/TestInterfaces/IDateTimeService.cs
test/TestInterfaces/TestInterfaces.csproj

Now it is possible to create grains with service dependencies.  Implement 'TestServiceProvider', use it with 'GrainCreator'. 
Look at "ServiceProbeTests.cs" for examples.

Add service probes

---

src/OrleansTestKit/TestGrainRuntime.cs
src/OrleansTestKit/TestKitSilo.cs
test/OrleansTestKit.Tests/DeactivationGrainTests.cs
test/OrleansTestKit.Tests/OrleansTestKit.Tests.csproj
test/TestGrains/DeactivationGrain.cs
test/TestGrains/TestGrains.csproj
test/TestInterfaces/IDeactivationGrain.cs
test/TestInterfaces/TestInterfaces.csproj

* add support for IGrainRuntime.DeactivateOnIdle()
* add support for IGrainRuntime.DelayDeactivation()
* both methods can be verified with TestKitSilo.VerifyRuntime()
Tests can be found here DeactivationGrainTests.cs

Support for IGrainRuntime.DeactivateOnIdle() and IGrainRuntime.DelayDeactivation()

---

.gitignore
src/OrleansTestKit/OrleansTestKit.csproj
src/OrleansTestKit/Reminders/TestReminderRegistry.cs
src/OrleansTestKit/TestGrainRuntime.cs
src/OrleansTestKit/TestKitSilo.cs
test/OrleansTestKit.Tests/OrleansTestKit.Tests.csproj
test/OrleansTestKit.Tests/ReminderTests.cs
test/OrleansTestKit.Tests/app.config
test/OrleansTestKit.Tests/packages.config
test/TestGrains/HelloReminders.cs
test/TestGrains/TestGrains.csproj

Mimic of Timer interface, but with reminders.

Added TestReminders

---

src/OrleansTestKit/Streams/TestStreamProviderManager.cs
test/OrleansTestKit.Tests/Tests/StreamTests.cs

Fixes #31 by allowing lazy creation of stream providers.

Enabled lazy stream providers again

---

src/OrleansTestKit/TestGrainLifecycle.cs
test/OrleansTestKit.Tests/Grains/StatefulActivationGrain.cs
test/OrleansTestKit.Tests/Tests/ActivationGrainTests.cs

Fixed NullReferenceException in Grain<T> OnActivateAsync #34

---

src/OrleansTestKit/TestGrainIdentity.cs
src/OrleansTestKit/TestKitSilo.cs
test/OrleansTestKit.Tests/Grains/BasicGrains.cs
test/OrleansTestKit.Tests/Interfaces/IBasicGrains.cs
test/OrleansTestKit.Tests/Tests/BasicGrainTests.cs
test/OrleansTestKit.Tests/Tests/TestGrainIdentityTests.cs

Need to test some grains with compound keys.

Support for compound key grains

---

src/OrleansTestKit/GrainProbeExtensions.cs
src/OrleansTestKit/TestGrainFactory.cs
test/OrleansTestKit.Tests/Grains/PingGrain.cs
test/OrleansTestKit.Tests/Interfaces/IPing.cs
test/OrleansTestKit.Tests/Interfaces/IPongCompound.cs
test/OrleansTestKit.Tests/Tests/GrainProbeTests.cs

Compound key Probes

---

src/OrleansTestKit/Streams/StreamExtensions.cs
test/OrleansTestKit.Tests/Grains/Chatty.cs
test/OrleansTestKit.Tests/Interfaces/IChatty.cs
test/OrleansTestKit.Tests/Tests/StreamTests.cs

Allow value types in streams

---

test/OrleansTestKit.Tests/Grains/DeviceManagerGrain.cs
test/OrleansTestKit.Tests/Interfaces/IDeviceManager.cs
test/OrleansTestKit.Tests/Tests/GrainProbeTests.cs

Fix polymorphic grain call tests

---

src/OrleansTestKit/OrleansTestKit.csproj
test/OrleansTestKit.Tests/OrleansTestKit.Tests.csproj

This updates to Orleans 2.3.3 and Moq 4.11.0.

Update NuGet dependencies

---

.editorconfig
src/OrleansTestKit/Streams/TestStream.cs
src/OrleansTestKit/Streams/TestStreamSubscriptionHandle.cs
test/OrleansTestKit.Tests/Tests/StreamTests.cs

Added Stream.GetAllSubscriptionHandles() implementation. Fixed editorconfig. Bug #62.

Added Stream.GetAllSubscriptionHandles() implementation

---

src/OrleansTestKit/Streams/TestStream.cs
test/OrleansTestKit.Tests/Grains/Chatty.cs
test/OrleansTestKit.Tests/Interfaces/IChatty.cs
test/OrleansTestKit.Tests/Tests/StreamTests.cs

compatibility(streams): support OnNextBatchAsync

---

src/OrleansTestKit/GrainProbeExtensions.cs
src/OrleansTestKit/OrleansTestKit.csproj
src/OrleansTestKit/TestGrainFactory.cs
test/OrleansTestKit.Tests/OrleansTestKit.Tests.csproj
test/OrleansTestKit.Tests/Tests/GrainProbeTests.cs

Removing Moq hard-dependency on AddProbe method
Adding tests

Removing Moq hard-dependency on AddProbe method

---

.editorconfig
Directory.Build.props
OrleansTestKit.sln
src/OrleansTestKit/Reminders/ReminderExtensions.cs
src/OrleansTestKit/Reminders/TestReminderRegistry.cs
src/OrleansTestKit/Storage/TestStorage.cs
src/OrleansTestKit/Streams/TestStream.cs
src/OrleansTestKit/Streams/TestStreamProvider.cs
src/OrleansTestKit/Streams/TestStreamProviderManager.cs
src/OrleansTestKit/Streams/TestStreamSubscriptionHandle.cs
src/OrleansTestKit/TestGrainActivationContext.cs
src/OrleansTestKit/TestGrainFactory.cs
src/OrleansTestKit/TestKitSilo.cs
src/OrleansTestKit/Timers/TestTimerRegistry.cs
src/OrleansTestKit/TypeHelper.cs

@seniorquico cleaned up a bunch of warning and added codedocs in a lot of places (not exhaustive yet)
Once this is in, I'm going to fix up the Test Stream so that it can handle Batch Streams

cleanup warnings and styling

---

.config/dotnet-tools.json
OrleansTestKit.sln
global.json
src/OrleansTestKit/OrleansTestKit.csproj
test/OrleansTestKit.Tests/OrleansTestKit.Tests.csproj

This prepares for a new beta release. It updates the project dependencies and bumps the NuGet package version to `beta.2`.

Update project dependencies and bump NuGet package version

---

src/OrleansTestKit/OrleansTestKit.csproj
src/OrleansTestKit/TestGrainActivationContext.cs
src/OrleansTestKit/TestGrainLifecycle.cs
test/OrleansTestKit.Tests/OrleansTestKit.Tests.csproj

Upgraded Orleans to 7.2.0.

---

src/OrleansTestKit/TestKitSilo.cs
test/OrleansTestKit.Tests/Grains/BasicGrains.cs
test/OrleansTestKit.Tests/Interfaces/IBasicGrains.cs
test/OrleansTestKit.Tests/Tests/GrainIdTests.cs

Resolve the GrainType from the provided generic grain value

---

Directory.Build.props
global.json
src/OrleansTestKit/OrleansTestKit.csproj
src/OrleansTestKit/Services/TestServiceProvider.cs
src/OrleansTestKit/Streams/TestStreamProviderManager.cs
src/OrleansTestKit/TestKitSilo.cs
test/OrleansTestKit.Tests/OrleansTestKit.Tests.csproj

Resolves  #149
Please note, I've updated nuget package verson to 8.0.0 to keeop it in sync with Orleans and .NET versioning (Orleans is already in sync with .NET).

Upgraded Orleans to version 8.0.0

---

.config/dotnet-tools.json
OrleansTestKit.sln
src/OrleansTestKit/OrleansTestKit.csproj
test/OrleansTestKit.Tests/OrleansTestKit.Tests.csproj

This prepares for a new v8 release. It upgrades the project dependencies and bumps the NuGet package version to 8.2.2.

Upgrade project dependencies and bump NuGet package version
