src/OrleansTestKit/TestGrainRuntime.cs, src/OrleansTestKit/TestKitSilo.cs, src/OrleansTestKit/Timers/TestTimer.cs, src/OrleansTestKit/Timers/TestTimerRegistry.cs, test/OrleansTestKit.Tests/OrleansTestKit.Tests.csproj, test/OrleansTestKit.Tests/TimerTests.cs, test/TestGrains/HelloTimers.cs, test/TestGrains/TestGrains.csproj
* uncomment test timer registry.
* add support for firing timer by index, in order of registration.
TimerTests.cs contains example of usage.
=> Timer registry support

.editorconfig, src/OrleansTestKit/OrleansTestKit.csproj, src/OrleansTestKit/Properties/AssemblyInfo.cs, src/OrleansTestKit/Streams/TestStreamSubscriptionHandle.cs, src/OrleansTestKit/TestGrainActivationContext.cs, src/OrleansTestKit/TestGrainCreator.cs, src/OrleansTestKit/TestGrainFactory.cs, src/OrleansTestKit/TestGrainIdentity.cs, src/OrleansTestKit/TestGrainRuntime.cs, src/OrleansTestKit/TestKitSilo.cs, src/OrleansTestKit/TypeHelper.cs, src/OrleansTestKit/app.config, src/OrleansTestKit/packages.config, test/OrleansTestKit.Tests/OrleansTestKit.Tests.csproj, test/OrleansTestKit.Tests/app.config, test/OrleansTestKit.Tests/packages.config, test/TestGrains/DeactivationGrain.cs, test/TestGrains/HelloGrain.cs, test/TestGrains/HelloTimers.cs, test/TestGrains/Listener.cs, test/TestGrains/TestGrains.csproj, test/TestGrains/app.config, test/TestGrains/packages.config, test/TestInterfaces/TestInterfaces.csproj, test/TestInterfaces/app.config, test/TestInterfaces/packages.config
This PR supersedes #13 and updates the test kit to work with Orleans v 1.5.
Orleans v1.5 makes `GrainCreator`, used by the test kit to instantiate grains, as `internal` meaning it cannot be used. I raised an issue on the Orleans repository about alternatives and was direct to [this thread](https://github.com/dotnet/orleans/issues/3086). The short answers seems to be that best way of unit testing a grain is to accept `IGrainRuntime` and `IGrainIdentity` in the constructor and let Orleans inject them for you in production. 
For the test kit this would mean either implementing some kind of primitive DI or using a container in conjunction with `TestServiceProvider`. The route of least resistance here seemed to be to create a `TestGrainCreator` type that mirrors the functionality of the …
=> Update to Orleans v1.5

src/OrleansTestKit/TestKitSilo.cs
This PR allows stream probes to be created for providers other than `Default`:
```csharp
this.Silo.AddStreamProbe<Message>(Guid.Empty, null, "Messages");
```
=> Allow stream probes to be created for providers other than 'Default'

src/OrleansTestKit/Storage/TestStorage.cs, src/OrleansTestKit/Streams/TestStreamProvider.cs, src/OrleansTestKit/TestGrainFactory.cs, src/OrleansTestKit/TestKitSilo.cs, test/OrleansTestKit.Tests/GrainProbeTests.cs, test/OrleansTestKit.Tests/StrictGrainProbeTests.cs, test/TestGrains/HelloReminders.cs, test/TestGrains/TestGrains.csproj
This PR adds the ability to specify a factory function to be used when creating grain probes in non-strict mode.
```csharp
this.Silo.AddProbeFactory<IPong>(identity => new Mock<IPong>());
```
A factory is only used when creating a grain if no specific grain already exists and the mode is non-strict.
=> Probe factories for non-strict probe grains

src/OrleansTestKit/TestKitSilo.cs, src/OrleansTestKit/TestServiceProvider.cs, test/OrleansTestKit.Tests/ServiceProbeTests.cs
Sometimes it's is necessary to supply an instance of a service instead of it's mock.
=> Add ability to supply a service instance

src/OrleansTestKit/GrainProbeExtensions.cs, src/OrleansTestKit/OrleansTestKit.csproj, src/OrleansTestKit/Reminders/ReminderExtensions.cs, src/OrleansTestKit/Services/TestServicesExtensions.cs, src/OrleansTestKit/Storage/StorageExtensions.cs, src/OrleansTestKit/Streams/StreamExtensions.cs, src/OrleansTestKit/TestGrainCreator.cs, src/OrleansTestKit/Timers/TimerExtensions.cs
Change TestKitt project to netstandard2.0. Closes #28 Good catch ;)
=> Changed to netstandard2.0. Moved all silo extension to Testkit namespace

src/OrleansTestKit/GrainProbeExtensions.cs
Closes #30. Now the probe will ensure that the key argument matches the key type specified in the IGrainWith___Key interface.
=> Cleaned up grain probe api to ensure the key type matches the grain type

src/OrleansTestKit/OrleansTestKit.csproj, src/OrleansTestKit/TestGrainLifecycle.cs, src/OrleansTestKit/TestKitSilo.cs, test/OrleansTestKit.Tests/Grains/StatefulActivationGrain.cs, test/OrleansTestKit.Tests/Tests/ActivationGrainTests.cs, test/OrleansTestKit.Tests/Tests/BasicGrainTests.cs, test/OrleansTestKit.Tests/Tests/DIGrainTests.cs, test/OrleansTestKit.Tests/Tests/DeactivationGrainTests.cs, test/OrleansTestKit.Tests/Tests/GrainProbeTests.cs, test/OrleansTestKit.Tests/Tests/LoggerTests.cs, test/OrleansTestKit.Tests/Tests/ReminderTests.cs, test/OrleansTestKit.Tests/Tests/ServiceProbeTests.cs, test/OrleansTestKit.Tests/Tests/StorageTests.cs, test/OrleansTestKit.Tests/Tests/StreamTests.cs, test/OrleansTestKit.Tests/Tests/StrictGrainProbeTests.cs, test/OrleansTestKit.Tests/Tests/StrictStreamTests.cs, test/OrleansTestKit.Tests/Tests/TimerTests.cs
When running the OrleansTestKit-based tests for a project in a VSTS (Visual Studio Online) build/release pipeline, we were getting failed streamprobe subscription count assertions. The tests pass locally on our dev machines, but when debugging with breakpoints we were finally able to recreate a similar problem.  Specifically we were seeing Subscription count assertions for registered StreamProbes would be wrong based on where we set breakpoints and how long we waited to proceed debugging. We speculated that `OnActivatedAsync` was an asynchronous method that was getting kicked off by `Silo.CreateGrain<T>()` (a non-asynchronous method).
Today I spent some time and found what I think is the "smoking gun" for this behavior:
```
Task.WaitAll(tasks.ToArray(), 1000);
```
in TestGrainLifecycle.cs …
=> Add Silo.CreateGrainAsync<T>() support and tests

src/OrleansTestKit/Timers/TestTimerRegistry.cs, test/OrleansTestKit.Tests/Grains/HelloTimers.cs
Fix an InvalidOperationException if new timers are created during FireAll() method call.
=> Fix InvalidOperationException in TestTimerRegistry.FireAll()

src/OrleansTestKit/TestKitSilo.cs, src/OrleansTestKit/Timers/TimerExtensions.cs
Thanks to @srollinet in #51 for pointing out a silly typo. The `TimerReistry` property was spelled incorrectly. This change retains the misspelled property for backward compatibility but marks it as `Obsolete`. References should be updated to use the corrected `TimerRegistry` property.
=> Fixed `TimerRegistry` property name typo

src/OrleansTestKit/Reminders/TestReminderRegistry.cs, test/OrleansTestKit.Tests/Grains/HelloReminders.cs, test/OrleansTestKit.Tests/Tests/ReminderTests.cs
Fixed #45. Thanks to @christiansparre for the fix!
The `TestReminderRegistry` would throw a `KeyNotFoundException` while the runtime registry returns `null` if the reminder does not exist making testing non existent reminder behavior difficult.
This makes the `TestReminderRegistry` return `null` if the dictionary does not
contain a reminder with the provided reminder name.
There is also some minor changes to the `HelloReminders` test grain and a test of the changed behavior.
=> Change `TestReminderRegistry` to behave more like the runtime reminder registry

README.md
This simply documents the limitation identified in #47.
=> Document `GetPrimaryKey` extension method limitation

OrleansTestKit.sln, src/OrleansTestKit/OrleansTestKit.csproj, test/OrleansTestKit.Tests/OrleansTestKit.Tests.csproj
This updates to Orleans 2.3.2.
This _should_ fix #59, but only by forcing projects to update to Orleans 2.3.2. Note that there currently is no good solution for releasing OrleansTestKit packages in lock-step with Orleans. Additionally, there's not really a great solution to having a release on NuGet for every incremental version of Orleans. If this is a concern for your project, I'm definitely open to a discussion/potential solution.
=> Updated NuGet dependencies

src/OrleansTestKit/Streams/TestStream.cs, src/OrleansTestKit/Timers/TestTimerRegistry.cs, test/OrleansTestKit.Tests/Grains/Chatty.cs, test/OrleansTestKit.Tests/Tests/StreamTests.cs
Fixes #84. The mock stream provider will first copy the list of subscriptions before invoking the OnNextAsync callbacks to ensure the iterator doesn't throw an `InvalidOperationException`.
=> Fix unsubscribing from streams during OnNextAsync callback

README.md, src/OrleansTestKit/OrleansTestKit.csproj, src/OrleansTestKit/Storage/StorageManager.cs, src/OrleansTestKit/Storage/TestStorage.cs, src/OrleansTestKit/TestGrainActivationContext.cs, src/OrleansTestKit/TestGrainRuntime.cs, test/OrleansTestKit.Tests/Grains/StatefulNonNewActivationGrain.cs, test/OrleansTestKit.Tests/Tests/ActivationGrainTests.cs
- Update Microsoft.Orleans.OrleansRuntime Version to 3.1.1
- Update Version of OrleansTestKit to 3.1.0
- Update Copyright to include 2020
- Work around removed new() constraint of grainstates
=> Update Microsoft.Orleans.OrleansRuntime to version 3.1.1

src/OrleansTestKit/OrleansTestKit.csproj, src/OrleansTestKit/TestGrainActivationContext.cs
The RegistrationStrategy was removed in error, and Orleans 3.1.2 is a re-release of Orleans 3.1.1 that fixes build/packaging issues. Fixes #88.
=> Revert RegistrationStrategy change and upgrade to Orleans 3.1.2

global.json, src/OrleansTestKit/OrleansTestKit.csproj, test/OrleansTestKit.Tests/OrleansTestKit.Tests.csproj
Replaces `Microsoft.CodeAnalysis.FxCopAnalyzers` with `Microsoft.CodeAnalysis.NetAnalyzers` (see [docs](https://docs.microsoft.com/en-us/visualstudio/code-quality/migrate-from-fxcop-analyzers-to-net-analyzers?view=vs-2019)).
=> Migrate to new .NET analyzers

test/OrleansTestKit.Tests/Grains/IUnknownGrainResolver.cs, test/OrleansTestKit.Tests/Grains/PingGrain.cs, test/OrleansTestKit.Tests/Grains/UnknownGrainResolver.cs, test/OrleansTestKit.Tests/Interfaces/IPong.cs, test/OrleansTestKit.Tests/Interfaces/IUnknownGrain.cs, test/OrleansTestKit.Tests/Tests/GrainProbeTests.cs
Resolves #101 
It turns out there is already a test for a simple probe factory case, so I added one for the more complicated case where multiple grains are created, and probes need to be set up for each of them to return a value based on the id they actually end up being created with by the grain under test.
PS I extended the existing Ping/Pong test classes rather than creating new ones - can redo if required.
=> Added test for creating and mocking multiple grain probes

src/OrleansTestKit/Timers/TestTimer.cs, src/OrleansTestKit/Timers/TestTimerRegistry.cs, test/OrleansTestKit.Tests/Grains/HelloTimers.cs, test/OrleansTestKit.Tests/Tests/TimerTests.cs
Added the ability to track the number of active timers on a grain. Useful to see if a timer was set but without wanting to check if the callback had been called.
=> Adding ability to keep track of number of timers

.config/dotnet-tools.json, .editorconfig, .vscode/extensions.json, .vscode/settings.json, OrleansTestKit.code-workspace, OrleansTestKit.sln, global.json, src/OrleansTestKit/OrleansTestKit.csproj, src/OrleansTestKit/Storage/StorageExtensions.cs, src/OrleansTestKit/Storage/StorageManager.cs, src/OrleansTestKit/Streams/TestStream.cs, test/OrleansTestKit.Tests/OrleansTestKit.Tests.csproj, test/OrleansTestKit.Tests/Tests/BasicGrainTests.cs, test/OrleansTestKit.Tests/Tests/GrainProbeTests.cs, test/OrleansTestKit.Tests/Tests/LoggerTests.cs, test/OrleansTestKit.Tests/Tests/ReminderTests.cs, test/OrleansTestKit.Tests/Tests/StrictGrainProbeTests.cs
This updates the project to the latest .NET 5 SDK, and updates the test project to use a .NET 5 runtime. This also resolves & suppresses some additional code analysis warnings. The library target remains unchanged (.NET Standard 2.0).
=> Update dependencies and bump NuGet package version

src/OrleansTestKit/Streams/TestStream.cs, src/OrleansTestKit/Streams/TestStreamSubscriptionHandle.cs, test/OrleansTestKit.Tests/Tests/StreamTests.cs
This PR provides for retrieving the HandleId, ProviderName, and StreamIdentity when working with streams.   re: #116 we have logging routines which captured these values and would fail when testing using OrleansTestKit.
=> pass thru the id, provider, generate a handleid, generate streamidentity

src/OrleansTestKit/OrleansTestKit.csproj, src/OrleansTestKit/Storage/StorageExtensions.cs, src/OrleansTestKit/Storage/StorageManager.cs, src/OrleansTestKit/Storage/TestPersistentStateAttributeToFactoryMapper.cs, src/OrleansTestKit/Storage/TestStorage.cs, src/OrleansTestKit/TestGrainRuntime.cs, src/OrleansTestKit/TestKitSilo.cs, test/OrleansTestKit.Tests/Grains/ColorRankingGrain.cs, test/OrleansTestKit.Tests/Interfaces/IColorRankingGrain.cs, test/OrleansTestKit.Tests/Tests/PersistantStreamNotWithinGrainStateTests.cs, test/OrleansTestKit.Tests/Tests/PersistentStreamWithinGrainStateTests.cs, test/OrleansTestKit.Tests/Tests/StorageFacetTests.cs, test/OrleansTestKit.Tests/Tests/StorageTests.cs, test/OrleansTestKit.Tests/Tests/TimerTests.cs
This is based on @enewnham's helper method in the linked issue. I've extended it to allow you to add multiple persistent states on the grain identified by StateName and StorageName.
I had to change StorageManager to allow multiple storages to be registered. I didn't change the existing interface and instead made them default the state name to `Default`.
closes #55
=> Add method for adding PersistentState for grains using PersistentStateFacets

src/OrleansTestKit/TestGrainCreator.cs, src/OrleansTestKit/TestKitSilo.cs, src/OrleansTestKit/Utilities/RuntimeContextManager.cs, test/OrleansTestKit.Tests/Grains/ContextConstructorGrain.cs, test/OrleansTestKit.Tests/OrleansTestKit.Tests.csproj, test/OrleansTestKit.Tests/Tests/ContextConstructorGrainTests.cs
There are places in Orleans that require the RuntimeContext to be set (such as reminders) to ensure you are accessing from a grain context (not some background thread)
This change also fixes a couple of issues / inconsistencies:
1. Can access grain context / runtime in the grain's constructor
2. Can inject `IGrainContext` into grain dependencies as needed
3. Can access grain context / runtime in grain's lifecycle participation.
=> Set RuntimeContext and make IGrainContext injectable during Grain's construction / activation

.github/workflows/publish.yml, .github/workflows/release.yml
This fixes some GitHub Actions warnings that occurred due to setting custom variables during the jobs. There is a new style based on "environment files":
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> Fix GitHub Actions warnings on custom variables

.editorconfig, src/OrleansTestKit/Streams/StreamExtensions.cs, src/OrleansTestKit/Streams/TestStream.cs, src/OrleansTestKit/Streams/TestStreamProviderManager.cs, src/OrleansTestKit/Streams/TestStreamSubscriptionHandle.cs, test/OrleansTestKit.Tests/Grains/Chatty.cs, test/OrleansTestKit.Tests/Interfaces/IChatty.cs, test/OrleansTestKit.Tests/Tests/StreamBatchTests.cs, test/OrleansTestKit.Tests/Tests/StreamProbeStringTests.cs, test/OrleansTestKit.Tests/Tests/StreamTests.cs
Orleans 7 introduces string-based stream keys (not just Guid) -- this PR adds those overloads to the TestKit
Also added Batch Observer support to the TestKit -- emulated Orleans behaviors when invoking OnNextBatchAsync
=> Streaming Improvements - String-Based Stream Probes and Batch Observer Support

src/OrleansTestKit/Storage/StorageExtensions.cs, src/OrleansTestKit/Storage/StorageManager.cs, src/OrleansTestKit/Storage/TestPersistentStateAttributeToFactoryMapper.cs, src/OrleansTestKit/Storage/TestStorage.cs, src/OrleansTestKit/TestGrainRuntime.cs, src/OrleansTestKit/TestKitSilo.cs, test/OrleansTestKit.Tests/Grains/ColorRankingGrain.cs, test/OrleansTestKit.Tests/Interfaces/IColorRankingGrain.cs, test/OrleansTestKit.Tests/Tests/PersistantStreamNotWithinGrainStateTests.cs, test/OrleansTestKit.Tests/Tests/PersistentStreamWithinGrainStateTests.cs, test/OrleansTestKit.Tests/Tests/StorageFacetTests.cs, test/OrleansTestKit.Tests/Tests/StorageTests.cs, test/OrleansTestKit.Tests/Tests/TimerTests.cs
Hi there,
The changes in #105 got lost during the migration to orleans 7.0. This returns all the changes on top of main branch
Original issue: #55
=> Add back method support for PersistentStateFacets

Directory.Build.props, README.md
This updates the README in preparation for Orleans 8 support. We will follow the previous pattern, where we create a `4.x` branch for Orleans TestKit 4 with support for Orleans 7 and move the `main` branch to Orleans TestKit 8 with support for Orleans 8.
=> Update README in preparation for Orleans 8 support

README.md
This updates the README and removes the Orleans TestKit 4/Microsoft Orleans 7 note.
=> Update README for Orleans 8 support

src/OrleansTestKit/OrleansTestKit.csproj, src/OrleansTestKit/Reminders/ReminderContextHolder.cs, src/OrleansTestKit/Utilities/RuntimeContextManager.cs, test/OrleansTestKit.Tests/OrleansTestKit.Tests.csproj
=> Upgrade Orleans to version 8.1.0

src/OrleansTestKit/OrleansTestKit.csproj, src/OrleansTestKit/TestGrainActivationContext.cs, src/OrleansTestKit/TestGrainCreator.cs, src/OrleansTestKit/Timers/TestTimer.cs, src/OrleansTestKit/Timers/TestTimerRegistry.cs, test/OrleansTestKit.Tests/Grains/HelloTimers.cs, test/OrleansTestKit.Tests/OrleansTestKit.Tests.csproj, test/OrleansTestKit.Tests/Tests/TimerTests.cs
Update OrleansTestKit to work with [Orleans 8.2](https://github.com/dotnet/orleans/releases/tag/v8.2.0)
closes https://github.com/OrleansContrib/OrleansTestKit/issues/164
=> Update for Orleans 8.2

src/OrleansTestKit/TestKitSilo.cs, test/OrleansTestKit.Tests/Grains/ActivationCountWithReminder.cs, test/OrleansTestKit.Tests/Tests/ActivationGrainTests.cs
Test grain for tracking OnActivateAsync call count Test OnActivateAsync is only called once
fixes https://github.com/OrleansContrib/OrleansTestKit/issues/154
Also needed in 4.x branch
=> correct the double call to OnActivateAsync on IRemindable grains

src/OrleansTestKit/TestKitSilo.cs, test/OrleansTestKit.Tests/Grains/ActivationCountWithReminder.cs, test/OrleansTestKit.Tests/Tests/ActivationGrainTests.cs
backport of https://github.com/OrleansContrib/OrleansTestKit/pull/165
Test grain for tracking OnActivateAsync call count Test OnActivateAsync is only called once
for https://github.com/OrleansContrib/OrleansTestKit/issues/154 in the 4.x branch
=> (4.x backport) correct the double call to OnActivateAsync on IRemindable grains

.github/workflows/continuous-integration.yml, .github/workflows/release.yml, .vscode/settings.json, OrleansTestKit.sln, README.md, global.json, src/OrleansTestKit/OrleansTestKit.csproj, test/OrleansTestKit.Tests/OrleansTestKit.Tests.csproj
This prepares for a new v8 release. It upgrades the project dependencies and bumps the NuGet package version to 8.2.1.
Closes #167.
=> Upgrade project dependencies and bump NuGet package version
